### ISSUE TITLE
Testing new bibtex parser 

### ISSUE THREAD

**Issue by Azzaare** [ali-ramadhan/DocumenterCitations.jl#1]
Hi @ali-ramadhan ,

I have been changing a few things in BibParser.jl and Bibliography.jl. The syntax is the same as before, but you might see some changes (it should be improvements) here.

Could you check? Version of Bibliography.jl should be v0.2.1.

**Comment by ali-ramadhan** [comment]
Sorry for the super slow reply @Azzaare! We updated to Bibliography.jl v0.2.3 and looks like it works!

@charleskawczynski and I are trying to turn this package into a Documenter.jl plugin. Sorry for slacking on this repo.
