### ISSUE TITLE
Some documentation

### ISSUE THREAD

**Issue by ali-ramadhan** [ali-ramadhan/DocumenterCitations.jl#10]
It's just a Documenter.jl plugin so maybe we don't need to set up full docs to show how to use it? Maybe just some quick info the README should be enough to start with?

**Comment by kellertuer** [comment]
Thanks for starting this package. I am really looking forward trying this package, since we have quite some citations in our docs. So I would love to see maybe just the docs of this package as one large example? Otherwise, sure, examples in the readme would be nice, too.

**Comment by ali-ramadhan** [comment]
Hi @kellertuer, thanks for checking it out!

I opened a PR to add a quickstart to the README: https://github.com/ali-ramadhan/DocumenterCitations.jl/blob/ali/quickstart/README.md


And will try to work on deploying some docs over the next few days. Certainly it seems shameful if a Documenter.jl plugin is not well-documented 🙃

**Comment by kellertuer** [comment]
Great! Thanks for the start, I hope to find the time to test that soon on Manifolds.jl.

**Comment by ali-ramadhan** [comment]
Ended up writing up basic docs (not that there's much to the package yet) but until the PR is approved and merged you should be able to see the docs here: http://aliramadhan.me/DocumenterCitations.jl/previews/PR13/ (sorry for conflict between personal website and package docs...)

**Comment by kellertuer** [comment]
Thanks, that not only looks easy to use but with `(@cite)` also great!
