### ISSUE TITLE
Change `CitationBibliography` to `DocumenterBibliography`?

### ISSUE THREAD

**Issue by ali-ramadhan** [ali-ramadhan/DocumenterCitations.jl#16]
@charleskawczynski What do you think of changing `CitationBibliography` to `DocumenterBibliography`?

`CitationBibliography` sounds somewhat redundant while `DocumenterBibliography` might be a bit more descriptive.

**Comment by charleskawczynski** [comment]
I'm fine with changing it if you'd like. I found it tricky to come up with a good/intuitive name for this. I was thinking at the time: what should we call the struct indicating where all of the citations in this package are collected? Perhaps it would be a good idea to get input from the Julia community?

**Comment by simonbyrne** [comment]
Why not just `Bibliography`?

**Comment by ali-ramadhan** [comment]
Hmmm, `Bibliography` might conflict with Bibliography.jl.

Well, Bibliography.jl does not define a `Bibliography` type. It returns an `OrderedDict` when you call `import_bibtex("example.bib")` so `Bibliography` might be fine.

@Azzaare would it be safe if we used `Bibliography` or do you have plans to add a `Bibliography` type to Bibliography.jl? Perhaps it makes sense to share a `Bibliography` type here?

**Comment by simonbyrne** [comment]
I don't think it would work, because the `Bibliography` module would already be using the name (this is why a lot of packages are named with a plural).

**Comment by simonbyrne** [comment]
I think `CitationBibliography` is fine for now.

**Comment by simonbyrne** [comment]
In 1.6 you will be able to rename imports (https://github.com/JuliaLang/julia/pull/37396)
