### ISSUE TITLE
Sorting of bibliography entries

### ISSUE THREAD

**Issue by simonbyrne** [ali-ramadhan/DocumenterCitations.jl#28]
Can they be sorted by author-year?

c.f. https://github.com/CliMA/ClimateMachine.jl/pull/1687#issuecomment-720598681

**Comment by ali-ramadhan** [comment]
Don't think would would be super hard to implement. The bibliography is an ordered dict I think so we just have to iterate over the entries of the dict sorted by `xnames` or something:

https://github.com/ali-ramadhan/DocumenterCitations.jl/blob/4ccfced7749b7bc785dee018b0ffec7b1066f6f5/src/bibliography.jl#L42

**Comment by fingolfin** [comment]
This would be great to have. Currently, our bibliography looks like a random mess: https://oscar-system.github.io/Oscar.jl/dev/references/

**Comment by Azzaare** [comment]
New tag version on the way for Bibliography.jl that adds sorting option(s) thanks to @LazyScholar 

I suppose long term would need a lot of different sorting options, but it is a great start that should help in making the output of `DocumenterCitations.jl` less messy

**Comment by LazyScholar** [comment]
Merged #39 which brings a [documentation entry](http://aliramadhan.me/DocumenterCitations.jl/dev/#How-to-get-a-sorted-References-list) on how to use now.
Sorting is still rudimentary so have a look if it suffices for you for now or if some adjustments are necessary (if so please direct issues at `Bibliography.jl` or `BibInternal.jl` as the sorting mechanics are handled there).
https://github.com/Humans-of-Julia/Bibliography.jl/issues/17

**Comment by LazyScholar** [comment]
Merged #39 which brings a [documentation entry](http://aliramadhan.me/DocumenterCitations.jl/dev/#How-to-get-a-sorted-References-list) on how to use the sorting for now.
Sorting is still rudimentary so have a look if it is good enough for now or if some adjustments are necessary (if so please direct issues at `Bibliography.jl` or `BibInternal.jl` as the sorting mechanics are handled there).
https://github.com/Humans-of-Julia/Bibliography.jl/issues/17

**Comment by LazyScholar** [comment]
Sorry i was too fast...
For some reason https://github.com/ali-ramadhan/DocumenterCitations.jl/blob/8606536a10cd2c6328fd91cf0d4de180dad3b3a8/src/DocumenterCitations.jl#L27 recreates the Dictionary/OrderedDict and the ordering is lost. I have to investigate how to insert it into the `Documenter.Plugin` structure without loosing the ordering.

**Comment by LazyScholar** [comment]
Tested it on my tiny project 
__It should work now__.
