### ISSUE TITLE
Volume should be an optional field for article

### ISSUE THREAD

**Issue by andreasnoack** [ali-ramadhan/DocumenterCitations.jl#29]
For the bibtex info
```
@article{white1982maximum,
  title={Maximum likelihood estimation of misspecified models},
  author={White, Halbert},
  journal={Econometrica: Journal of the Econometric Society},
  pages={1--25},
  year={1982},
  publisher={JSTOR}
}
```
I'm getting
```julia
ERROR: LoadError: Entry white1982maximum is missing the volume field(s).
```
but `volume` is an optional field, see https://www.bibtex.com/e/article-entry/.

**Comment by charleskawczynski** [comment]
I ran into this also

**Comment by kellertuer** [comment]
This might be more an issue for the package https://github.com/Azzaare/Bibliography.jl ?

**Comment by ali-ramadhan** [comment]
Yeah I think so, but @Azzaare can maybe confirm.

I remember running into this so I just peppered some empty `volume = {}` entries but yeah `volume` should be an optional field.

**Comment by Azzaare** [comment]
@charleskawczynski Indeed, there was a mistake in the bibtex rules for Bibliography.jl. It should be updated soon.

**Comment by Azzaare** [comment]
This should be closed now I guess

**Comment by LazyScholar** [comment]
Works now. Checked it with the provided bibtex entry from above.
