### ISSUE TITLE
More compact citing, with verbose option

### ISSUE THREAD

**Issue by charleskawczynski** [ali-ramadhan/DocumenterCitations.jl#30]
Sometimes it's a bit too verbose to include all of the authors when citing a paper. For example:

<img width="840" alt="Screen Shot 2020-11-30 at 1 01 55 PM" src="https://user-images.githubusercontent.com/1880641/100664312-48446c80-330c-11eb-9784-ba05d3427ca7.png">

I would prefer `Harrington (1995)` or `Harrington et. al. (1995)`. I think it would be nice if the printed citation were compact, but maybe we can offer users an option to print them verbosely?

**Comment by simonbyrne** [comment]
Duplicate of #22?

**Comment by charleskawczynski** [comment]
Ah, yes. Sorry about that.
