### ISSUE TITLE
Configure CI

### ISSUE THREAD

**Issue by charleskawczynski** [ali-ramadhan/DocumenterCitations.jl#4]

**Comment by ali-ramadhan** [comment]
Hmmm, should probably figure out how to test this plugin haha.

@mortenpi might have some ideas?

**Comment by charleskawczynski** [comment]
My first naive thought would be to run documented in strict mode, and test that the references exist in the generated HTML, but maybe that's a bit of a kluge.

**Comment by ali-ramadhan** [comment]
That would still be a good test. Even if the links are wrong, at least it didn't error/crash and produced some docs with links.

**Comment by mortenpi** [comment]
I would suggest running a few small documentation builds as integration tests. We do that in [Documenter's own tests](https://github.com/JuliaDocs/Documenter.jl/blob/master/test/examples/).

**Comment by ali-ramadhan** [comment]
Thanks @mortenpi! Will look into Documenter.jl's tests and try to set some integration tests up here.
