### ISSUE TITLE
Convert TeX umlauts and accents also in `@ref` commands, not just the bibliography

### ISSUE THREAD

**Issue by fingolfin** [ali-ramadhan/DocumenterCitations.jl#50]
On https://oscar-system.github.io/Oscar.jl/dev/references/ the umlaut character like ö and ü appear just fine. E.g. the final entry is 
> Günter M. Ziegler, Lectures on polytopes, Springer-Verlag, New York, 1995.

But when they are cited, this is not the case, see e.g. https://oscar-system.github.io/Oscar.jl/dev/PolyhedralGeometry/pg/ where `[Zie95](@cite)` is rendered as:
> G\"{u}nter M. Ziegler (1995)

But ideally it would appear as
> Günter M. Ziegler (1995)

**Comment by LazyScholar** [comment]
@fingolfin can you check if #51 fixes you issue?
